require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

  # This is a list of cop names that are allowed to fail without exiting the
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false