require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false